/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { SbOrderService } from "../sbOrder.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { SbOrderCreateInput } from "./SbOrderCreateInput";
import { SbOrder } from "./SbOrder";
import { SbOrderFindManyArgs } from "./SbOrderFindManyArgs";
import { SbOrderWhereUniqueInput } from "./SbOrderWhereUniqueInput";
import { SbOrderUpdateInput } from "./SbOrderUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class SbOrderControllerBase {
  constructor(
    protected readonly service: SbOrderService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: SbOrder })
  @nestAccessControl.UseRoles({
    resource: "SbOrder",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  @swagger.ApiBody({
    type: SbOrderCreateInput,
  })
  async createSbOrder(
    @common.Body() data: SbOrderCreateInput
  ): Promise<SbOrder> {
    return await this.service.createSbOrder({
      data: {
        ...data,

        employeeId: data.employeeId
          ? {
              connect: data.employeeId,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        date: true,

        employeeId: {
          select: {
            id: true,
          },
        },

        id: true,
        shift: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [SbOrder] })
  @ApiNestedQuery(SbOrderFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "SbOrder",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async sbOrders(@common.Req() request: Request): Promise<SbOrder[]> {
    const args = plainToClass(SbOrderFindManyArgs, request.query);
    return this.service.sbOrders({
      ...args,
      select: {
        createdAt: true,
        date: true,

        employeeId: {
          select: {
            id: true,
          },
        },

        id: true,
        shift: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: SbOrder })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "SbOrder",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async sbOrder(
    @common.Param() params: SbOrderWhereUniqueInput
  ): Promise<SbOrder | null> {
    const result = await this.service.sbOrder({
      where: params,
      select: {
        createdAt: true,
        date: true,

        employeeId: {
          select: {
            id: true,
          },
        },

        id: true,
        shift: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: SbOrder })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "SbOrder",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  @swagger.ApiBody({
    type: SbOrderUpdateInput,
  })
  async updateSbOrder(
    @common.Param() params: SbOrderWhereUniqueInput,
    @common.Body() data: SbOrderUpdateInput
  ): Promise<SbOrder | null> {
    try {
      return await this.service.updateSbOrder({
        where: params,
        data: {
          ...data,

          employeeId: data.employeeId
            ? {
                connect: data.employeeId,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          date: true,

          employeeId: {
            select: {
              id: true,
            },
          },

          id: true,
          shift: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: SbOrder })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "SbOrder",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteSbOrder(
    @common.Param() params: SbOrderWhereUniqueInput
  ): Promise<SbOrder | null> {
    try {
      return await this.service.deleteSbOrder({
        where: params,
        select: {
          createdAt: true,
          date: true,

          employeeId: {
            select: {
              id: true,
            },
          },

          id: true,
          shift: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
