/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { DbEmployeeService } from "../dbEmployee.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { DbEmployeeCreateInput } from "./DbEmployeeCreateInput";
import { DbEmployee } from "./DbEmployee";
import { DbEmployeeFindManyArgs } from "./DbEmployeeFindManyArgs";
import { DbEmployeeWhereUniqueInput } from "./DbEmployeeWhereUniqueInput";
import { DbEmployeeUpdateInput } from "./DbEmployeeUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class DbEmployeeControllerBase {
  constructor(
    protected readonly service: DbEmployeeService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: DbEmployee })
  @nestAccessControl.UseRoles({
    resource: "DbEmployee",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  @swagger.ApiBody({
    type: DbEmployeeCreateInput,
  })
  async createDbEmployee(
    @common.Body() data: DbEmployeeCreateInput
  ): Promise<DbEmployee> {
    return await this.service.createDbEmployee({
      data: {
        ...data,

        companyId: data.companyId
          ? {
              connect: data.companyId,
            }
          : undefined,

        sbEmployees: data.sbEmployees
          ? {
              connect: data.sbEmployees,
            }
          : undefined,
      },
      select: {
        companyId: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,
        name: true,

        sbEmployees: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [DbEmployee] })
  @ApiNestedQuery(DbEmployeeFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "DbEmployee",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async dbEmployees(@common.Req() request: Request): Promise<DbEmployee[]> {
    const args = plainToClass(DbEmployeeFindManyArgs, request.query);
    return this.service.dbEmployees({
      ...args,
      select: {
        companyId: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,
        name: true,

        sbEmployees: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: DbEmployee })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "DbEmployee",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async dbEmployee(
    @common.Param() params: DbEmployeeWhereUniqueInput
  ): Promise<DbEmployee | null> {
    const result = await this.service.dbEmployee({
      where: params,
      select: {
        companyId: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,
        name: true,

        sbEmployees: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: DbEmployee })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "DbEmployee",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  @swagger.ApiBody({
    type: DbEmployeeUpdateInput,
  })
  async updateDbEmployee(
    @common.Param() params: DbEmployeeWhereUniqueInput,
    @common.Body() data: DbEmployeeUpdateInput
  ): Promise<DbEmployee | null> {
    try {
      return await this.service.updateDbEmployee({
        where: params,
        data: {
          ...data,

          companyId: data.companyId
            ? {
                connect: data.companyId,
              }
            : undefined,

          sbEmployees: data.sbEmployees
            ? {
                connect: data.sbEmployees,
              }
            : undefined,
        },
        select: {
          companyId: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          id: true,
          name: true,

          sbEmployees: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: DbEmployee })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "DbEmployee",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteDbEmployee(
    @common.Param() params: DbEmployeeWhereUniqueInput
  ): Promise<DbEmployee | null> {
    try {
      return await this.service.deleteDbEmployee({
        where: params,
        select: {
          companyId: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          id: true,
          name: true,

          sbEmployees: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
