/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { DbEmployeeWhereUniqueInput } from "../../dbEmployee/base/DbEmployeeWhereUniqueInput";
import { ValidateNested, IsOptional } from "class-validator";
import { Type } from "class-transformer";
import { StringFilter } from "../../util/StringFilter";
import { SbPickupPointWhereUniqueInput } from "../../sbPickupPoint/base/SbPickupPointWhereUniqueInput";
import { SbOrderListRelationFilter } from "../../sbOrder/base/SbOrderListRelationFilter";
import { SbVehicleWhereUniqueInput } from "../../sbVehicle/base/SbVehicleWhereUniqueInput";

@InputType()
class SbEmployeeWhereInput {
  @ApiProperty({
    required: false,
    type: () => DbEmployeeWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => DbEmployeeWhereUniqueInput)
  @IsOptional()
  @Field(() => DbEmployeeWhereUniqueInput, {
    nullable: true,
  })
  employeeId?: DbEmployeeWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: () => SbPickupPointWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => SbPickupPointWhereUniqueInput)
  @IsOptional()
  @Field(() => SbPickupPointWhereUniqueInput, {
    nullable: true,
  })
  pickupPointId?: SbPickupPointWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: () => SbOrderListRelationFilter,
  })
  @ValidateNested()
  @Type(() => SbOrderListRelationFilter)
  @IsOptional()
  @Field(() => SbOrderListRelationFilter, {
    nullable: true,
  })
  sbOrders?: SbOrderListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => SbVehicleWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => SbVehicleWhereUniqueInput)
  @IsOptional()
  @Field(() => SbVehicleWhereUniqueInput, {
    nullable: true,
  })
  shift_1UnitId?: SbVehicleWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: () => SbVehicleWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => SbVehicleWhereUniqueInput)
  @IsOptional()
  @Field(() => SbVehicleWhereUniqueInput, {
    nullable: true,
  })
  shift_2UnitId?: SbVehicleWhereUniqueInput;
}

export { SbEmployeeWhereInput as SbEmployeeWhereInput };
