/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { SbEmployeeService } from "../sbEmployee.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { SbEmployeeCreateInput } from "./SbEmployeeCreateInput";
import { SbEmployee } from "./SbEmployee";
import { SbEmployeeFindManyArgs } from "./SbEmployeeFindManyArgs";
import { SbEmployeeWhereUniqueInput } from "./SbEmployeeWhereUniqueInput";
import { SbEmployeeUpdateInput } from "./SbEmployeeUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class SbEmployeeControllerBase {
  constructor(
    protected readonly service: SbEmployeeService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: SbEmployee })
  @nestAccessControl.UseRoles({
    resource: "SbEmployee",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createSbEmployee(
    @common.Body() data: SbEmployeeCreateInput
  ): Promise<SbEmployee> {
    return await this.service.createSbEmployee({
      data: {
        ...data,

        employee: data.employee
          ? {
              connect: data.employee,
            }
          : undefined,

        pickupPoint: data.pickupPoint
          ? {
              connect: data.pickupPoint,
            }
          : undefined,

        sbOrders: data.sbOrders
          ? {
              connect: data.sbOrders,
            }
          : undefined,

        vehicleNoShift_1: data.vehicleNoShift_1
          ? {
              connect: data.vehicleNoShift_1,
            }
          : undefined,

        vehicleNoShift_2: data.vehicleNoShift_2
          ? {
              connect: data.vehicleNoShift_2,
            }
          : undefined,
      },
      select: {
        createdAt: true,

        employee: {
          select: {
            id: true,
          },
        },

        id: true,

        pickupPoint: {
          select: {
            id: true,
          },
        },

        sbOrders: {
          select: {
            id: true,
          },
        },

        updatedAt: true,

        vehicleNoShift_1: {
          select: {
            id: true,
          },
        },

        vehicleNoShift_2: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [SbEmployee] })
  @ApiNestedQuery(SbEmployeeFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "SbEmployee",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async sbEmployees(@common.Req() request: Request): Promise<SbEmployee[]> {
    const args = plainToClass(SbEmployeeFindManyArgs, request.query);
    return this.service.sbEmployees({
      ...args,
      select: {
        createdAt: true,

        employee: {
          select: {
            id: true,
          },
        },

        id: true,

        pickupPoint: {
          select: {
            id: true,
          },
        },

        sbOrders: {
          select: {
            id: true,
          },
        },

        updatedAt: true,

        vehicleNoShift_1: {
          select: {
            id: true,
          },
        },

        vehicleNoShift_2: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: SbEmployee })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "SbEmployee",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async sbEmployee(
    @common.Param() params: SbEmployeeWhereUniqueInput
  ): Promise<SbEmployee | null> {
    const result = await this.service.sbEmployee({
      where: params,
      select: {
        createdAt: true,

        employee: {
          select: {
            id: true,
          },
        },

        id: true,

        pickupPoint: {
          select: {
            id: true,
          },
        },

        sbOrders: {
          select: {
            id: true,
          },
        },

        updatedAt: true,

        vehicleNoShift_1: {
          select: {
            id: true,
          },
        },

        vehicleNoShift_2: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: SbEmployee })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "SbEmployee",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateSbEmployee(
    @common.Param() params: SbEmployeeWhereUniqueInput,
    @common.Body() data: SbEmployeeUpdateInput
  ): Promise<SbEmployee | null> {
    try {
      return await this.service.updateSbEmployee({
        where: params,
        data: {
          ...data,

          employee: data.employee
            ? {
                connect: data.employee,
              }
            : undefined,

          pickupPoint: data.pickupPoint
            ? {
                connect: data.pickupPoint,
              }
            : undefined,

          sbOrders: data.sbOrders
            ? {
                connect: data.sbOrders,
              }
            : undefined,

          vehicleNoShift_1: data.vehicleNoShift_1
            ? {
                connect: data.vehicleNoShift_1,
              }
            : undefined,

          vehicleNoShift_2: data.vehicleNoShift_2
            ? {
                connect: data.vehicleNoShift_2,
              }
            : undefined,
        },
        select: {
          createdAt: true,

          employee: {
            select: {
              id: true,
            },
          },

          id: true,

          pickupPoint: {
            select: {
              id: true,
            },
          },

          sbOrders: {
            select: {
              id: true,
            },
          },

          updatedAt: true,

          vehicleNoShift_1: {
            select: {
              id: true,
            },
          },

          vehicleNoShift_2: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: SbEmployee })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "SbEmployee",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteSbEmployee(
    @common.Param() params: SbEmployeeWhereUniqueInput
  ): Promise<SbEmployee | null> {
    try {
      return await this.service.deleteSbEmployee({
        where: params,
        select: {
          createdAt: true,

          employee: {
            select: {
              id: true,
            },
          },

          id: true,

          pickupPoint: {
            select: {
              id: true,
            },
          },

          sbOrders: {
            select: {
              id: true,
            },
          },

          updatedAt: true,

          vehicleNoShift_1: {
            select: {
              id: true,
            },
          },

          vehicleNoShift_2: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
